#!/bin/sh

# **
# checks if command "$1" is installed;
#
# verifies if the file is an executable file, this is used to prevent
# conflicts with user-defined aliases and functions
# *

[ -x "$(command -v "$1")" ]
