#!/bin/sh

# TODO: `-x` is not portable

# **
# Checks if command "$1" is installed
#
# verifies if the file is an executable file, this is used to prevent
# conflicts with user-defined aliases and functions
# *

# shellcheck disable=2006
# backtick notation is portable

test -x "`command -v "$1"`"
