#!/bin/sh

# **
# Checks if invoking user is root
# *

# shellcheck disable=2046
# cannot quote as we are comparing integers
# shellcheck disable=2006
# backtick notation is portable

test `id -u` -eq 0
